version: '3.8'

services:
  # Spring Boot 애플리케이션 서비스

  # MySQL 데이터베이스 서비스
  db:
    image: mysql:8.0
    container_name: sfaas-db
    environment:
      MYSQL_DATABASE: sfaas_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql # 데이터를 영구적으로 보존하기 위해 볼륨을 사용합니다.
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: